name = "icing-space-press"
main = "index.js"
compatibility_date = "2022-11-25"
usage_model = "unbound"
node_compat = true
routes = [
    { pattern = "icing.space", custom_domain = true },
    { pattern = "www.icing.space", custom_domain = true }
]
# env = {}

[triggers]
crons = []

[dev]
port = 4329
